export const VPN_CONFIG = {
    "appUpNotes": "No Updates!",
    "appBuildVersion": "1",
    "applicationLink": "www.google.com",
    "FileName": "fixConfig",
    "Version": "6.85",
    "ReleaseNotes": "All User Info👇\n\n🇸🇦Mobily Free All Area✈️✅\n🇸🇦Zain Free Test Added✅\nSTC FREE NEW Server Added\n\n🇸🇦Mobily 30/60/115 SR Package All Area\n🇸🇦STC Free All Area\n🇸🇦Salam Free All Area\n🇸🇦Redbull 60 SR Package",
    "contactSupport": "google.com",
    "config_url": "https://raw.githubusercontent.com/FixBuildApp/JsonUpdater/refs/heads/main/vpnconfig.json",
    "account_api": "https://cloudv2rayvip.top/api/geleekai/auth?",
    "AppConfPass": "1:2-3:4",
    "Servers": [
        {
            "Name": "Afghanistan Server 01",
            "serverType": "3",
            "sUdpObfs": "",
            "FLAG": "afghanistan",
            "Category": "0",
            "V2rayType": "0",
            "V2rayMainID": "11c0e8a5-944e-49e9-b369-47bd5a48fa5e",
            "VnetCertExp": "",
            "TrackPostExp": "",
            "ServerIP": "",
            "ServerCloudFront": "vless://[fixkey]@[fixhost]:443?security=tls&encryption=none&type=ws&host=rop1-1079145771511.europe-north1.run.app&path=/kobe&sni=[fixhost]&fp=chrome#443GCP",
            "ServerHTTP": "",
            "TcpPort": "1194:53",
            "SSLPort": "443",
            "ProxyHost": "",
            "ProxyPort": "",
            "AutoLogIn": "false",
            "SecureConnection": "false",
            "Username": "",
            "Password": "",
            "MultiCert": "false",
            "ovpnCertificate": "",
            "Server_msg": "High Speed",
            "Server_exp_box": "false",
            "Server_exp": "0-spliter-8:49 am",
            "server_web_renew": "www.vpnjantit.com"
        },
        {
            "Name": "Algeria Server 02",
            "serverType": "3",
            "sUdpObfs": "",
            "FLAG": "algeria",
            "Category": "0",
            "V2rayType": "0",
            "V2rayMainID": "4e75e5f8-9ee5-4afa-991d-5688c3d798ea",
            "VnetCertExp": "",
            "TrackPostExp": "",
            "ServerIP": "",
            "ServerCloudFront": "vless://[fixkey]@[fixhost]:443?security=tls&encryption=none&type=ws&host=rop2-1079145771511.europe-north1.run.app&path=/kobe&sni=[fixhost]&fp=chrome#443GCP",
            "ServerHTTP": "",
            "TcpPort": "1194:53",
            "SSLPort": "443",
            "ProxyHost": "",
            "ProxyPort": "",
            "AutoLogIn": "false",
            "SecureConnection": "false",
            "Username": "",
            "Password": "",
            "MultiCert": "false",
            "ovpnCertificate": "",
            "Server_msg": "High Speed",
            "Server_exp_box": "false",
            "Server_exp": "0-spliter-8:49 am",
            "server_web_renew": "www.vpnjantit.com"
        },
        {
            "Name": "Argentina Server 03",
            "serverType": "3",
            "sUdpObfs": "",
            "FLAG": "argentina",
            "Category": "0",
            "V2rayType": "0",
            "V2rayMainID": "9d8a5a4b-5bb4-48f1-9a3e-2bdeff5f086f",
            "VnetCertExp": "",
            "TrackPostExp": "",
            "ServerIP": "",
            "ServerCloudFront": "vless://[fixkey]@[fixhost]:443?security=tls&encryption=none&type=ws&host=rop3-1079145771511.europe-north1.run.app&path=/kobe&sni=[fixhost]&fp=chrome#443GCP",
            "ServerHTTP": "",
            "TcpPort": "1194:53",
            "SSLPort": "443",
            "ProxyHost": "",
            "ProxyPort": "",
            "AutoLogIn": "false",
            "SecureConnection": "false",
            "Username": "",
            "Password": "",
            "MultiCert": "false",
            "ovpnCertificate": "",
            "Server_msg": "High Speed",
            "Server_exp_box": "false",
            "Server_exp": "0-spliter-8:49 am",
            "server_web_renew": "www.vpnjantit.com"
        },
        {
            "Name": "Australia Server 04",
            "serverType": "3",
            "sUdpObfs": "",
            "FLAG": "australia",
            "Category": "0",
            "V2rayType": "0",
            "V2rayMainID": "5f6788d7-1992-457d-8fd2-4ef92167c645",
            "VnetCertExp": "",
            "TrackPostExp": "",
            "ServerIP": "",
            "ServerCloudFront": "vless://[fixkey]@[fixhost]:443?security=tls&encryption=none&type=ws&host=rop4-1079145771511.europe-north1.run.app&path=/kobe&sni=[fixhost]&fp=chrome#443GCP",
            "ServerHTTP": "",
            "TcpPort": "1194:53",
            "SSLPort": "443",
            "ProxyHost": "",
            "ProxyPort": "",
            "AutoLogIn": "false",
            "SecureConnection": "false",
            "Username": "",
            "Password": "",
            "MultiCert": "false",
            "ovpnCertificate": "",
            "Server_msg": "High Speed",
            "Server_exp_box": "false",
            "Server_exp": "0-spliter-8:49 am",
            "server_web_renew": "www.vpnjantit.com"
        },
        {
            "Name": "Austria Server 05",
            "serverType": "3",
            "sUdpObfs": "",
            "FLAG": "austria",
            "Category": "0",
            "V2rayType": "0",
            "V2rayMainID": "c1334fc2-9e0a-40de-b24f-e320cb2bf0dc",
            "VnetCertExp": "",
            "TrackPostExp": "",
            "ServerIP": "",
            "ServerCloudFront": "vless://[fixkey]@[fixhost]:443?security=tls&encryption=none&type=ws&host=rop5-1079145771511.europe-north1.run.app&path=/kobe&sni=[fixhost]&fp=chrome#443GCP",
            "ServerHTTP": "",
            "TcpPort": "1194:53",
            "SSLPort": "443",
            "ProxyHost": "",
            "ProxyPort": "",
            "AutoLogIn": "false",
            "SecureConnection": "false",
            "Username": "",
            "Password": "",
            "MultiCert": "false",
            "ovpnCertificate": "",
            "Server_msg": "High Speed",
            "Server_exp_box": "false",
            "Server_exp": "0-spliter-8:49 am",
            "server_web_renew": "www.vpnjantit.com"
        },
        {
            "Name": "Dynamic Server 6",
            "serverType": "3",
            "sUdpObfs": "",
            "FLAG": "bahrain",
            "Category": "0",
            "V2rayType": "0",
            "V2rayMainID": "93e798d2-3054-4a11-a9ba-a3f3b15a8efb",
            "VnetCertExp": "",
            "TrackPostExp": "",
            "ServerIP": "",
            "ServerCloudFront": "vless://[fixkey]@[fixhost]:443?security=tls&encryption=none&type=ws&host=rop6-1079145771511.europe-north1.run.app&path=/kobe&sni=[fixhost]&fp=chrome#443GCP",
            "ServerHTTP": "",
            "TcpPort": "1194:53",
            "SSLPort": "443",
            "ProxyHost": "",
            "ProxyPort": "",
            "AutoLogIn": "false",
            "SecureConnection": "false",
            "Username": "",
            "Password": "",
            "MultiCert": "false",
            "ovpnCertificate": "",
            "Server_msg": "Cloud V2Ray ViP",
            "Server_exp_box": "false",
            "Server_exp": "0-spliter-8:49 am",
            "server_web_renew": "www.vpnjantit.com"
        },
        {
            "Name": "Bangladesh Server 07",
            "serverType": "3",
            "sUdpObfs": "",
            "FLAG": "bangladesh",
            "Category": "0",
            "V2rayType": "0",
            "V2rayMainID": "6d36adcd-d46c-489c-b87e-98d8d284e186",
            "VnetCertExp": "",
            "TrackPostExp": "",
            "ServerIP": "",
            "ServerCloudFront": "vless://[fixkey]@[fixhost]:443?security=tls&encryption=none&type=ws&host=rop7-1079145771511.europe-north1.run.app&path=/kobe&sni=[fixhost]&fp=chrome#443GCP",
            "ServerHTTP": "",
            "TcpPort": "1194:53",
            "SSLPort": "443",
            "ProxyHost": "",
            "ProxyPort": "",
            "AutoLogIn": "false",
            "SecureConnection": "false",
            "Username": "",
            "Password": "",
            "MultiCert": "false",
            "ovpnCertificate": "",
            "Server_msg": "High Speed",
            "Server_exp_box": "false",
            "Server_exp": "0-spliter-8:50 am",
            "server_web_renew": "www.vpnjantit.com"
        },
        {
            "Name": "Belgium Server 08",
            "serverType": "3",
            "sUdpObfs": "",
            "FLAG": "belgium",
            "Category": "0",
            "V2rayType": "0",
            "V2rayMainID": "664724f2-8d69-4d33-89c3-83a89e8fb9b8",
            "VnetCertExp": "",
            "TrackPostExp": "",
            "ServerIP": "",
            "ServerCloudFront": "vless://[fixkey]@[fixhost]:443?security=tls&encryption=none&type=ws&host=rop8-1079145771511.europe-north1.run.app&path=/kobe&sni=[fixhost]&fp=chrome#443GCP",
            "ServerHTTP": "",
            "TcpPort": "1194:53",
            "SSLPort": "443",
            "ProxyHost": "",
            "ProxyPort": "",
            "AutoLogIn": "false",
            "SecureConnection": "false",
            "Username": "",
            "Password": "",
            "MultiCert": "false",
            "ovpnCertificate": "",
            "Server_msg": "High Speed",
            "Server_exp_box": "false",
            "Server_exp": "0-spliter-8:50 am",
            "server_web_renew": "www.vpnjantit.com"
        },
        {
            "Name": "Benin Server 09",
            "serverType": "3",
            "sUdpObfs": "",
            "FLAG": "benin",
            "Category": "0",
            "V2rayType": "0",
            "V2rayMainID": "df8b6956-2053-430f-a97f-9f6b4eac2849",
            "VnetCertExp": "",
            "TrackPostExp": "",
            "ServerIP": "",
            "ServerCloudFront": "vless://[fixkey]@[fixhost]:443?security=tls&encryption=none&type=ws&host=rop9-1079145771511.europe-north1.run.app&path=/kobe&sni=[fixhost]&fp=chrome#443GCP",
            "ServerHTTP": "",
            "TcpPort": "1194:53",
            "SSLPort": "443",
            "ProxyHost": "",
            "ProxyPort": "",
            "AutoLogIn": "false",
            "SecureConnection": "false",
            "Username": "",
            "Password": "",
            "MultiCert": "false",
            "ovpnCertificate": "",
            "Server_msg": "High Speed",
            "Server_exp_box": "false",
            "Server_exp": "0-spliter-8:50 am",
            "server_web_renew": "www.vpnjantit.com"
        },
        {
            "Name": "Bulgaria Server 10",
            "serverType": "3",
            "sUdpObfs": "",
            "FLAG": "bulgaria",
            "Category": "0",
            "V2rayType": "0",
            "V2rayMainID": "ab70e588-3ca1-4460-81ff-8b52bd0bf184",
            "VnetCertExp": "",
            "TrackPostExp": "",
            "ServerIP": "",
            "ServerCloudFront": "vless://[fixkey]@[fixhost]:443?security=tls&encryption=none&type=ws&host=rop10-1079145771511.europe-north1.run.app&path=/kobe&sni=[fixhost]&fp=chrome#443GCP",
            "ServerHTTP": "",
            "TcpPort": "1194:53",
            "SSLPort": "443",
            "ProxyHost": "",
            "ProxyPort": "",
            "AutoLogIn": "false",
            "SecureConnection": "false",
            "Username": "",
            "Password": "",
            "MultiCert": "false",
            "ovpnCertificate": "",
            "Server_msg": "High Speed",
            "Server_exp_box": "false",
            "Server_exp": "0-spliter-8:50 am",
            "server_web_renew": "www.vpnjantit.com"
        }
    ],
    "HTTPNetworks": [
        {
            "FLAG": "mobily",
            "proto_spin": "6",
            "server_type": "cf",
            "Name": "Mobily 30 SR Mashawir/Taxi Bundle 💡🚕",
            "NetworkPayload": "",
            "NetworkHostConfig": "maps.google.com",
            "SecureQuery": "",
            "isSecureV2ray": "false",
            "V2rayPayloadType": "0",
            "ProtoServerType": "0",
            "Info": "(Send: 1100 Type: 8294)(All Area Good Working💥)",
            "UseDefProxy": "true",
            "AutoReplace": "false",
            "SquidProxy": "[Default]",
            "SquidPort": "8080",
            "NetworkFrontQuery": "",
            "NetworkBackQuery": ""
        },
        {
            "FLAG": "mobily",
            "proto_spin": "6",
            "server_type": "cf",
            "Name": "Mobily 30 SR Mashawir Pack1️⃣💡",
            "NetworkPayload": "",
            "NetworkHostConfig": "maps.gstatic.com",
            "SecureQuery": "",
            "isSecureV2ray": "false",
            "V2rayPayloadType": "0",
            "ProtoServerType": "0",
            "Info": "(Send: 1100 Type: 8294)(All Area Good Working💥)",
            "UseDefProxy": "true",
            "AutoReplace": "false",
            "SquidProxy": "[Default]",
            "SquidPort": "8080",
            "NetworkFrontQuery": "",
            "NetworkBackQuery": ""
        },
        {
            "FLAG": "stc",
            "proto_spin": "6",
            "server_type": "cf",
            "Name": "STC Free ViP 2025",
            "NetworkPayload": "",
            "NetworkHostConfig": "172.65.90.47",
            "SecureQuery": "",
            "isSecureV2ray": "false",
            "V2rayPayloadType": "1",
            "ProtoServerType": "0",
            "Info": "(Try To Flight Mode On OFF✈️)",
            "UseDefProxy": "true",
            "AutoReplace": "false",
            "SquidProxy": "[Default]",
            "SquidPort": "8080",
            "NetworkFrontQuery": "",
            "NetworkBackQuery": ""
        },
        {
            "FLAG": "zain",
            "proto_spin": "6",
            "server_type": "cf",
            "Name": "Zain Free ViP New✅",
            "NetworkPayload": "",
            "NetworkHostConfig": "www.secure5gw.ro",
            "SecureQuery": "",
            "isSecureV2ray": "false",
            "V2rayPayloadType": "1",
            "ProtoServerType": "0",
            "Info": "",
            "UseDefProxy": "true",
            "AutoReplace": "false",
            "SquidProxy": "[Default]",
            "SquidPort": "8080",
            "NetworkFrontQuery": "",
            "NetworkBackQuery": ""
        },
        {
            "FLAG": "jawwy",
            "proto_spin": "0",
            "server_type": "cf",
            "Name": "Jawwy Free Dammam Makkah Area",
            "NetworkPayload": "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]",
            "NetworkHostConfig": "",
            "SecureQuery": "",
            "isSecureV2ray": "false",
            "V2rayPayloadType": "0",
            "ProtoServerType": "1",
            "Info": "(Unlimited Interet✅)",
            "UseDefProxy": "false",
            "AutoReplace": "false",
            "SquidProxy": "paymentservices.payfort.com",
            "SquidPort": "80",
            "NetworkFrontQuery": "",
            "NetworkBackQuery": ""
        },
        {
            "FLAG": "lebara",
            "proto_spin": "0",
            "server_type": "cf",
            "Name": "Lebara Free V2ray✅",
            "NetworkPayload": "",
            "NetworkHostConfig": "",
            "SecureQuery": "",
            "isSecureV2ray": "false",
            "V2rayPayloadType": "0",
            "ProtoServerType": "1",
            "Info": "(High Speed💥 All Area)",
            "UseDefProxy": "false",
            "AutoReplace": "false",
            "SquidProxy": "",
            "SquidPort": "80",
            "NetworkFrontQuery": "",
            "NetworkBackQuery": ""
        }
    ]
};
